version: "3.9"
services:
  db:
    image: postgres:15
    continers_name: postgressDB
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: apiusuarios
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data